<?php

// edited from "root" and "root" to "DiDit" and "mh1981mh" for username and password
$MYSQL_HOSTNAME = "localhost";
$MYSQL_USERNAME = "root";
$MYSQL_PASSWORD = "root";
$MYSQL_DATABASE = "DiDit";

/* edited from "root" and "root" to "DiDit" and "mh1981mh" for username and password
$MYSQL_HOSTNAME = "localhost";
$MYSQL_USERNAME = "DiDit";
$MYSQL_PASSWORD = "mh1981mh";
$MYSQL_DATABASE = "DiDit";
*/


?>